f = open('student.txt', mode = 'w', encoding='utf-8')

print('File Name: ',f.name)
print('file mode: ',f.mode)
print('File readable: ',f.readable())
print('file writeable: ',f.writable())
print('file cloased: ',f.closed)
f.close()
print("file closed: ",f.closed)
print()
print()

# f = open('student1.txt', mode = 'x', encoding='utf-8')

# print('File Name: ',f.name)
# print('file mode: ',f.mode)
# print('File readable: ',f.readable())
# print('file writeable: ',f.writable())
# print('file cloased: ',f.closed)
# f.close()
# print("file closed: ",f.closed)

f = open('student1.txt', mode = 'r+', encoding='utf-8')

print('File Name: ',f.name)
print('file mode: ',f.mode)
print('File readable: ',f.readable())
print('file writeable: ',f.writable())
print('file cloased: ',f.closed)
f.close()
print("file closed: ",f.closed)
print()
print()

f = open('student1.txt', mode = 'w+', encoding='utf-8')

print('File Name: ',f.name)
print('file mode: ',f.mode)
print('File readable: ',f.readable())
print('file writeable: ',f.writable())
print('file cloased: ',f.closed)
f.close()
print("file closed: ",f.closed)
print()
print()

f = open('Wallpaper.jpg', mode = 'r')

print('File Name: ',f.name)
print('file mode: ',f.mode)
print('File readable: ',f.readable())
print('file writeable: ',f.writable())
print('file cloased: ',f.closed)
f.close()
print("file closed: ",f.closed)
print()
print()
